#! /usr/bin/env bash

file="$1"
quiet=""

usage() {
    prog=$(basename "$0")
    echo "$prog [media filename]"
    exit -1
}

msg() {
    if [[ "$quiet" != "yes" ]]; then
        echo "$@"
    fi
}

genePreview(){
    msg gene preview image
    ffmpeg -ss 00:00:01 -i "$file" -r 1 -vframes 1 -an -f mjpeg -y "$file.jpg" 2>/dev/null
}

geneMarkdown(){
    msg gene markdown from mediainfo
    mdtoadata "$file"
}

main() {
    if [[ "$file" == "" ]]; then
        usage
    fi
    genePreview
    geneMarkdown
}

main
